#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

main() {
  BUMP_FIELD=patch
  parse_options "$@"

  cd ${SCRIPT_DIR}/..

  cargo set-version --bump $BUMP_FIELD

  if [[ $COMMIT == "yes" ]]; then
    local lock_arg
    # Include Cargo.lock if it's not ignored.
    grep Cargo.lock "$SCRIPT_DIR/../.gitignore" >& /dev/null || lock_arg=Cargo.lock
    git commit Cargo.toml $lock_arg -m "Bump $BUMP_FIELD to $(grep '^version' Cargo.toml | awk -F'"' '{print $2}')"
  fi
}

parse_options() {
  while [[ -n ${1} ]]; do
    case ${1} in
      -c | --commit)
        COMMIT=yes
        ;;
      --maj | --major)
        BUMP_FIELD=major
        ;;
      --min | --minor)
        BUMP_FIELD=minor
        ;;
      *)
        usage
        ;;
    esac

    shift
  done
}

usage() {
  log "Increments the version in Cargo.toml"
  log ""
  log "Usage:"
  log "${YELLOW}$(basename "$0") [OPTIONS]"
  log ""
  log "Options:"
  log "${YELLOW}-c, --commit   -- Commit the updated Cargo.toml"
  log "${YELLOW}--maj, --major -- Bump the major field (default is the patch field)"
  log "${YELLOW}--min, --minor -- Bump the minor field (default is the patch field)"
  log ""

  exit
}

# Define some colors:
black='\x1b[0;30m'; red='\x1b[0;31m'; green='\x1b[0;32m'; yellow='\x1b[0;33m'; blue='\x1b[0;34m'; pink='\x1b[0;35m'; cyan='\x1b[0;36m'; grey='\x1b[0;37m';
BLACK='\x1b[1;30m'; RED='\x1b[1;31m'; GREEN='\x1b[1;32m'; YELLOW='\x1b[1;33m'; BLUE='\x1b[1;34m'; PINK='\x1b[1;35m'; CYAN='\x1b[1;36m'; WHITE='\x1b[1;37m'
NC='\x1b[0m' # No Color

log() {
  echo -e "${CYAN}$*$NC" 1>&2
}

main "$@"
